### PR TITLE
Fix #11, Implemented cFE Table Service

### LINKED ISSUE #11: Schedule App not using CFE Table
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Schedule lab App is not using cFE table service. Recommend implementing cFE table service.

**Describe alternatives you've considered**
None

**Additional context**
none

**Requester Info**
Anh Van, NASA Goddard

### LINKED ISSUE #17: Simplify table path in CMakeList.txt
**Is your feature request related to a problem? Please describe.**
fsw/src is ignored in:

https://github.com/nasa/sch_lab/blob/e226d55d76621a8247286ba150e20e2edd51111c/CMakeLists.txt#L14

**Describe the solution you'd like**
Remove path, since it implies a specific file, when the build system actually searches the *_defs first for a matching file.

**Describe alternatives you've considered**
None

**Additional context**
See the guide in elf2cfetbl

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by avan989**
**Describe the contribution**
Fix #11, Implemented cFE table service

**Testing performed**
Steps taken to test the contribution:
1. Build 
2. Used GroundSystem to enable telemetry
3. Used Cosmos to verify package received:
          a. CFE_ES  - HK_TLM_PKT
          b. CFDP – CFDP_ENGINE_HK
          c. CFE_EVS – HK_TML_PKT
          d. CFE_SB – HK_TLM_PKT
          e. CFE_TBL = HK_TLM_PKT
          f. CFE_TIME – HK_TLM_PKT
          g. KIT_CI – HK_TLM_PKT
          h. KIT_TO – HK_TLM_PKT
          i.  UNKOWN 

4. Systematically removed each individual MID from table and verify:
        a. Removed CFE_ES_SEND_HK_MID. Verify CFE_ES is not receiving
        b. Removed CFE_EVS_SEND_HK_MID. Verify CFE_EVS is not receiving
        c. Removed CFE_TIME_SEND_HK_MID. Verify CFE_TIME is not receiving
        d. Removed CFE_SB_SEND_HK_MID. Verify CFE_SB is not receiving
        e. Removed CFE_TBL_SEND_HK_MID. Verify CFE_TBL is not receiving
        f. Removed CI_LAB_SEND_HK_MID. Verify Kit-CI is not receiving
        g. Removed TO_LAB_SEND_HK_MID.  Verify Kit-To is not receiving any package
        h. Removed SAMPLE_APP_SEND_HK_MID. Verify Unknown is not receiving any package

*Note - Sample_App correspond to Unknown in Cosmos

**Expected behavior changes**
No impact to behavior.

**System(s) tested on:**
 - Hardware
 - OS: Ubuntu 18.04.03
 - Cosmos 4.4.0 (part of OpenSatKit), GroundSystem 2.0.90a , cFE 6.6.0a, OSAL 1.4.2a

**Additional context**
None

**Contributor Info**
Anh Van, NASA Goddard

**Community contributors**
You must attach a signed CLA (required for acceptance) or reference one already submitted

### CODE REVIEW

**Comment by avan989** [comment]
do you mean update title and comment? or do you mean update the title name and commit name?

**Comment by skliper** [comment]
It's helpful if you can amend the commit comment to match the preferred format to make the integration candidate and merge process simpler:

Fix #x, Short Description

Long description (if needed)

**Comment by avan989** [comment]
Title and commit changed.

**Comment by avan989** [comment]
messed up. Restart pull requst

**Pull request closed without merging**
