### PR TITLE
Fix #54, Use MSG APIs

### LINKED ISSUE #54: Remove dependencies on deprecated SB APIs
**Is your feature request related to a problem? Please describe.**
SB APIs deprecated in nasa/cFE#777

**Describe the solution you'd like**
Update to use MSG module.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Requester Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by skliper**
**Describe the contribution**
Replaces deprecated SB API's with MSG
Fix #54

**Testing performed**
Built and ran, enabled telemetry, checked noops

**Expected behavior changes**
None

**System(s) tested on**
 - Hardware: cFS Dev Server
 - OS: Ubuntu 18.04
 - Versions: Bundle main + this commit

**Additional context**
nasa/cFE#777

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

### CODE REVIEW

**Comment by astrogeco** [comment]
[CCB 2020-11-12](https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-November-12-2020) APPROVED

**Comment by jphickey** [comment]
FWIW - I am still of the opinion we should hold off on making changes to apps until we have the correct API alignment patterns/requirements settled as per https://github.com/nasa/cfe/issues/1009#issuecomment-726258988

(Or in other words, there might be a good reason to keep the local TLM union buffer around)

**Comment by skliper** [comment]
Can this move forward?  I'm doing changes for nasa/cFE#1009 on top of these... aka #56.

**Review by jphickey — APPROVED** [review]
Yes, I think we have agreement on the path forward here.

**Pull request merged**
